# All other configurations will inherit from this file
# Configuration for Eureka server
eureka:
  instance:
    # Hostname for the Eureka instance
    hostname: localhost
  client:
    serviceUrl:
      # URL for the Eureka server
      defaultZone: http://localhost:8761/eureka/
  spring:
    cloud:
      config:
        # Prevent the config server from overriding system properties
        override-system-properties: false

management:
  tracing:
    sampling:
      probability: 1.0
  endpoint:
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, *
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true